In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('spy_wide_strikes_default_2023-09-01_to_2025-08-30_schema.csv')

In [7]:
pd.set_option('display.max_rows', 215)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Column       215 non-null    object
 1   Type         215 non-null    object
 2   Description  215 non-null    object
dtypes: object(3)
memory usage: 5.2+ KB

In [9]:
df

,Column,Type,Description
0,date,object,Trading date in YYYY-MM-DD format
1,spy_open,float64,SPY opening price for the day
2,spy_high,float64,SPY highest price for the day
3,spy_low,float64,SPY lowest price for the day
4,spy_close,float64,SPY closing price for the day
5,spy_close_prev_day,float64,SPY previous day closing price
6,spy_volume,float64,SPY trading volume for the day
7,expiration_date,object,Option expiration date
8,atm_strike,int64,Strike price for atm
9,atm_call_ticker,object,Option ticker symbol for atm call
10,atm_call_open,float64,Open price for atm call option
11,atm_call_high,float64,High price for atm call option
12,atm_call_low,float64,Low price for atm call option
13,atm_call_close,float64,Close price for atm call option
14,atm_call_volume,int64,Trading volume for atm call option
15,atm_call_vwap,float64,Volume-weighted average price for atm call option
16,atm_call_prev_open,float64,Previous day open for atm call option
17,atm_call_prev_close,float64,Previous day close for atm call option
18,atm_call_prev_volume,int64,Previous day volume for atm call option
19,atm_call_prev_vwap,float64,Previous day vwap for atm call option
20,atm_put_ticker,object,Option ticker symbol for atm put
21,atm_put_open,float64,Open price for atm put option
22,atm_put_high,float64,High price for atm put option
23,atm_put_low,float64,Low price for atm put option
24,atm_put_close,float64,Close price for atm put option
25,atm_put_volume,int64,Trading volume for atm put option
26,atm_put_vwap,float64,Volume-weighted average price for atm put option
27,atm_put_prev_open,float64,Previous day open for atm put option
28,atm_put_prev_close,float64,Previous day close for atm put option
29,atm_put_prev_volume,int64,Previous day volume for atm put option
30,atm_put_prev_vwap,float64,Previous day vwap for atm put option
31,plus_1_strike,int64,Strike price for plus_1
32,plus_1_call_ticker,object,Option ticker symbol for plus_1 call
33,plus_1_call_open,float64,Open price for plus_1 call option
34,plus_1_call_high,float64,High price for plus_1 call option
35,plus_1_call_low,float64,Low price for plus_1 call option
36,plus_1_call_close,float64,Close price for plus_1 call option
37,plus_1_call_volume,int64,Trading volume for plus_1 call option
38,plus_1_call_vwap,float64,Volume-weighted average price for plus_1 call ...
39,plus_1_call_prev_open,float64,Previous day open for plus_1 call option
40,plus_1_call_prev_close,float64,Previous day close for plus_1 call option
41,plus_1_call_prev_volume,float64,Previous day volume for plus_1 call option
42,plus_1_call_prev_vwap,float64,Previous day vwap for plus_1 call option
43,plus_1_put_ticker,object,Option ticker symbol for plus_1 put
44,plus_1_put_open,float64,Open price for plus_1 put option
45,plus_1_put_high,float64,High price for plus_1 put option
46,plus_1_put_low,float64,Low price for plus_1 put option
47,plus_1_put_close,float64,Close price for plus_1 put option
48,plus_1_put_volume,int64,Trading volume for plus_1 put option
49,plus_1_put_vwap,float64,Volume-weighted average price for plus_1 put o...
50,plus_1_put_prev_open,float64,Previous day open for plus_1 put option
51,plus_1_put_prev_close,float64,Previous day close for plus_1 put option
52,plus_1_put_prev_volume,float64,Previous day volume for plus_1 put option
53,plus_1_put_prev_vwap,float64,Previous day vwap for plus_1 put option
54,plus_2_strike,int64,Strike price for plus_2
55,plus_2_call_ticker,object,Option ticker symbol for plus_2 call
56,plus_2_call_open,float64,Open price for plus_2 call option
57,plus_2_call_high,float64,High price for plus_2 call option
58,plus_2_call_low,float64,Low price for plus_2 call option
59,plus_2_call_close,float64,Close price for plus_2 call option
60,plus_2_call_volume,float64,Trading volume for plus_2 call option
61,plus_2_call_vwap,float64,Volume-weighted average price for plus_2 call ...
62,plus_2_call_prev_open,float64,Previous day open for plus_2 call option
63,plus_2_call_prev_close,float64,Previous day close for plus_2 call option
64,plus_2_call_prev_volume,float64,Previous day volume for plus_2 call option
65,plus_2_call_prev_vwap,float64,Previous day vwap for plus_2 call option
66,plus_2_put_ticker,object,Option ticker symbol for plus_2 put
67,plus_2_put_open,float64,Open price for plus_2 put option
68,plus_2_put_high,float64,High price for plus_2 put option
69,plus_2_put_low,float64,Low price for plus_2 put option
70,plus_2_put_close,float64,Close price for plus_2 put option
71,plus_2_put_volume,float64,Trading volume for plus_2 put option
72,plus_2_put_vwap,float64,Volume-weighted average price for plus_2 put o...
73,plus_2_put_prev_open,float64,Previous day open for plus_2 put option
74,plus_2_put_prev_close,float64,Previous day close for plus_2 put option
75,plus_2_put_prev_volume,float64,Previous day volume for plus_2 put option
76,plus_2_put_prev_vwap,float64,Previous day vwap for plus_2 put option
77,plus_3_strike,int64,Strike price for plus_3
78,plus_3_call_ticker,object,Option ticker symbol for plus_3 call
79,plus_3_call_open,float64,Open price for plus_3 call option
80,plus_3_call_high,float64,High price for plus_3 call option
81,plus_3_call_low,float64,Low price for plus_3 call option
82,plus_3_call_close,float64,Close price for plus_3 call option
83,plus_3_call_volume,float64,Trading volume for plus_3 call option
84,plus_3_call_vwap,float64,Volume-weighted average price for plus_3 call ...
85,plus_3_call_prev_open,float64,Previous day open for plus_3 call option
86,plus_3_call_prev_close,float64,Previous day close for plus_3 call option
87,plus_3_call_prev_volume,float64,Previous day volume for plus_3 call option
88,plus_3_call_prev_vwap,float64,Previous day vwap for plus_3 call option
89,plus_3_put_ticker,object,Option ticker symbol for plus_3 put
90,plus_3_put_open,float64,Open price for plus_3 put option
91,plus_3_put_high,float64,High price for plus_3 put option
92,plus_3_put_low,float64,Low price for plus_3 put option
93,plus_3_put_close,float64,Close price for plus_3 put option
94,plus_3_put_volume,float64,Trading volume for plus_3 put option
95,plus_3_put_vwap,float64,Volume-weighted average price for plus_3 put o...
96,plus_3_put_prev_open,float64,Previous day open for plus_3 put option
97,plus_3_put_prev_close,float64,Previous day close for plus_3 put option
98,plus_3_put_prev_volume,float64,Previous day volume for plus_3 put option
99,plus_3_put_prev_vwap,float64,Previous day vwap for plus_3 put option
100,plus_4_strike,int64,Strike price for plus_4
101,plus_4_call_ticker,object,Option ticker symbol for plus_4 call
102,plus_4_call_open,float64,Open price for plus_4 call option
103,plus_4_call_high,float64,High price for plus_4 call option
104,plus_4_call_low,float64,Low price for plus_4 call option
105,plus_4_call_close,float64,Close price for plus_4 call option
106,plus_4_call_volume,float64,Trading volume for plus_4 call option
107,plus_4_call_vwap,float64,Volume-weighted average price for plus_4 call ...
108,plus_4_call_prev_open,float64,Previous day open for plus_4 call option
109,plus_4_call_prev_close,float64,Previous day close for plus_4 call option
110,plus_4_call_prev_volume,float64,Previous day volume for plus_4 call option
111,plus_4_call_prev_vwap,float64,Previous day vwap for plus_4 call option
112,plus_4_put_ticker,object,Option ticker symbol for plus_4 put
113,plus_4_put_open,float64,Open price for plus_4 put option
114,plus_4_put_high,float64,High price for plus_4 put option
115,plus_4_put_low,float64,Low price for plus_4 put option
116,plus_4_put_close,float64,Close price for plus_4 put option
117,plus_4_put_volume,float64,Trading volume for plus_4 put option
118,plus_4_put_vwap,float64,Volume-weighted average price for plus_4 put o...
119,plus_4_put_prev_open,float64,Previous day open for plus_4 put option
120,plus_4_put_prev_close,float64,Previous day close for plus_4 put option
121,plus_4_put_prev_volume,float64,Previous day volume for plus_4 put option
122,plus_4_put_prev_vwap,float64,Previous day vwap for plus_4 put option
123,plus_5_strike,int64,Strike price for plus_5
124,plus_5_call_ticker,object,Option ticker symbol for plus_5 call
125,plus_5_call_open,float64,Open price for plus_5 call option
126,plus_5_call_high,float64,High price for plus_5 call option
127,plus_5_call_low,float64,Low price for plus_5 call option
128,plus_5_call_close,float64,Close price for plus_5 call option
129,plus_5_call_volume,float64,Trading volume for plus_5 call option
130,plus_5_call_vwap,float64,Volume-weighted average price for plus_5 call ...
131,plus_5_call_prev_open,float64,Previous day open for plus_5 call option
132,plus_5_call_prev_close,float64,Previous day close for plus_5 call option
133,plus_5_call_prev_volume,float64,Previous day volume for plus_5 call option
134,plus_5_call_prev_vwap,float64,Previous day vwap for plus_5 call option
135,plus_5_put_ticker,object,Option ticker symbol for plus_5 put
136,plus_5_put_open,float64,Open price for plus_5 put option
137,plus_5_put_high,float64,High price for plus_5 put option
138,plus_5_put_low,float64,Low price for plus_5 put option
139,plus_5_put_close,float64,Close price for plus_5 put option
140,plus_5_put_volume,float64,Trading volume for plus_5 put option
141,plus_5_put_vwap,float64,Volume-weighted average price for plus_5 put o...
142,plus_5_put_prev_open,float64,Previous day open for plus_5 put option
143,plus_5_put_prev_close,float64,Previous day close for plus_5 put option
144,plus_5_put_prev_volume,float64,Previous day volume for plus_5 put option
145,plus_5_put_prev_vwap,float64,Previous day vwap for plus_5 put option
146,minus_1_strike,int64,Strike price for minus_1
147,minus_1_call_ticker,object,Option ticker symbol for minus_1 call
148,minus_1_call_open,float64,Open price for minus_1 call option
149,minus_1_call_high,float64,High price for minus_1 call option
150,minus_1_call_low,float64,Low price for minus_1 call option
151,minus_1_call_close,float64,Close price for minus_1 call option
152,minus_1_call_volume,int64,Trading volume for minus_1 call option
153,minus_1_call_vwap,float64,Volume-weighted average price for minus_1 call...
154,minus_1_call_prev_open,float64,Previous day open for minus_1 call option
155,minus_1_call_prev_close,float64,Previous day close for minus_1 call option
156,minus_1_call_prev_volume,int64,Previous day volume for minus_1 call option
157,minus_1_call_prev_vwap,float64,Previous day vwap for minus_1 call option
158,minus_1_put_ticker,object,Option ticker symbol for minus_1 put
159,minus_1_put_open,float64,Open price for minus_1 put option
160,minus_1_put_high,float64,High price for minus_1 put option
161,minus_1_put_low,float64,Low price for minus_1 put option
162,minus_1_put_close,float64,Close price for minus_1 put option
163,minus_1_put_volume,int64,Trading volume for minus_1 put option
164,minus_1_put_vwap,float64,Volume-weighted average price for minus_1 put ...
165,minus_1_put_prev_open,float64,Previous day open for minus_1 put option
166,minus_1_put_prev_close,float64,Previous day close for minus_1 put option
167,minus_1_put_prev_volume,int64,Previous day volume for minus_1 put option
168,minus_1_put_prev_vwap,float64,Previous day vwap for minus_1 put option
169,minus_2_strike,int64,Strike price for minus_2
170,minus_2_call_ticker,object,Option ticker symbol for minus_2 call
171,minus_2_call_open,float64,Open price for minus_2 call option
172,minus_2_call_high,float64,High price for minus_2 call option
173,minus_2_call_low,float64,Low price for minus_2 call option
174,minus_2_call_close,float64,Close price for minus_2 call option
175,minus_2_call_volume,int64,Trading volume for minus_2 call option
176,minus_2_call_vwap,float64,Volume-weighted average price for minus_2 call...
177,minus_2_call_prev_open,float64,Previous day open for minus_2 call option
178,minus_2_call_prev_close,float64,Previous day close for minus_2 call option
179,minus_2_call_prev_volume,int64,Previous day volume for minus_2 call option
180,minus_2_call_prev_vwap,float64,Previous day vwap for minus_2 call option
181,minus_2_put_ticker,object,Option ticker symbol for minus_2 put
182,minus_2_put_open,float64,Open price for minus_2 put option
183,minus_2_put_high,float64,High price for minus_2 put option
184,minus_2_put_low,float64,Low price for minus_2 put option
185,minus_2_put_close,float64,Close price for minus_2 put option
186,minus_2_put_volume,int64,Trading volume for minus_2 put option
187,minus_2_put_vwap,float64,Volume-weighted average price for minus_2 put ...
188,minus_2_put_prev_open,float64,Previous day open for minus_2 put option
189,minus_2_put_prev_close,float64,Previous day close for minus_2 put option
190,minus_2_put_prev_volume,int64,Previous day volume for minus_2 put option
191,minus_2_put_prev_vwap,float64,Previous day vwap for minus_2 put option
192,minus_3_strike,int64,Strike price for minus_3
193,minus_3_call_ticker,object,Option ticker symbol for minus_3 call
194,minus_3_call_open,float64,Open price for minus_3 call option
195,minus_3_call_high,float64,High price for minus_3 call option
196,minus_3_call_low,float64,Low price for minus_3 call option
197,minus_3_call_close,float64,Close price for minus_3 call option
198,minus_3_call_volume,int64,Trading volume for minus_3 call option
199,minus_3_call_vwap,float64,Volume-weighted average price for minus_3 call...
200,minus_3_call_prev_open,float64,Previous day open for minus_3 call option
201,minus_3_call_prev_close,float64,Previous day close for minus_3 call option
202,minus_3_call_prev_volume,int64,Previous day volume for minus_3 call option
203,minus_3_call_prev_vwap,float64,Previous day vwap for minus_3 call option
204,minus_3_put_ticker,object,Option ticker symbol for minus_3 put
205,minus_3_put_open,float64,Open price for minus_3 put option
206,minus_3_put_high,float64,High price for minus_3 put option
207,minus_3_put_low,float64,Low price for minus_3 put option
208,minus_3_put_close,float64,Close price for minus_3 put option
209,minus_3_put_volume,int64,Trading volume for minus_3 put option
210,minus_3_put_vwap,float64,Volume-weighted average price for minus_3 put ...
211,minus_3_put_prev_open,float64,Previous day open for minus_3 put option
212,minus_3_put_prev_close,float64,Previous day close for minus_3 put option
213,minus_3_put_prev_volume,int64,Previous day volume for minus_3 put option
214,minus_3_put_prev_vwap,float64,Previous day vwap for minus_3 put option

In [9]:
df

,Column,Type,Description
0,date,object,Trading date in YYYY-MM-DD format
1,spy_open,float64,SPY opening price for the day
2,spy_high,float64,SPY highest price for the day
3,spy_low,float64,SPY lowest price for the day
4,spy_close,float64,SPY closing price for the day
5,spy_close_prev_day,float64,SPY previous day closing price
6,spy_volume,float64,SPY trading volume for the day
7,expiration_date,object,Option expiration date
8,atm_strike,int64,Strike price for atm
9,atm_call_ticker,object,Option ticker symbol for atm call
10,atm_call_open,float64,Open price for atm call option
11,atm_call_high,float64,High price for atm call option
12,atm_call_low,float64,Low price for atm call option
13,atm_call_close,float64,Close price for atm call option
14,atm_call_volume,int64,Trading volume for atm call option
15,atm_call_vwap,float64,Volume-weighted average price for atm call option
16,atm_call_prev_open,float64,Previous day open for atm call option
17,atm_call_prev_close,float64,Previous day close for atm call option
18,atm_call_prev_volume,int64,Previous day volume for atm call option
19,atm_call_prev_vwap,float64,Previous day vwap for atm call option
20,atm_put_ticker,object,Option ticker symbol for atm put
21,atm_put_open,float64,Open price for atm put option
22,atm_put_high,float64,High price for atm put option
23,atm_put_low,float64,Low price for atm put option
24,atm_put_close,float64,Close price for atm put option
25,atm_put_volume,int64,Trading volume for atm put option
26,atm_put_vwap,float64,Volume-weighted average price for atm put option
27,atm_put_prev_open,float64,Previous day open for atm put option
28,atm_put_prev_close,float64,Previous day close for atm put option
29,atm_put_prev_volume,int64,Previous day volume for atm put option
30,atm_put_prev_vwap,float64,Previous day vwap for atm put option
31,plus_1_strike,int64,Strike price for plus_1
32,plus_1_call_ticker,object,Option ticker symbol for plus_1 call
33,plus_1_call_open,float64,Open price for plus_1 call option
34,plus_1_call_high,float64,High price for plus_1 call option
35,plus_1_call_low,float64,Low price for plus_1 call option
36,plus_1_call_close,float64,Close price for plus_1 call option
37,plus_1_call_volume,int64,Trading volume for plus_1 call option
38,plus_1_call_vwap,float64,Volume-weighted average price for plus_1 call ...
39,plus_1_call_prev_open,float64,Previous day open for plus_1 call option
40,plus_1_call_prev_close,float64,Previous day close for plus_1 call option
41,plus_1_call_prev_volume,float64,Previous day volume for plus_1 call option
42,plus_1_call_prev_vwap,float64,Previous day vwap for plus_1 call option
43,plus_1_put_ticker,object,Option ticker symbol for plus_1 put
44,plus_1_put_open,float64,Open price for plus_1 put option
45,plus_1_put_high,float64,High price for plus_1 put option
46,plus_1_put_low,float64,Low price for plus_1 put option
47,plus_1_put_close,float64,Close price for plus_1 put option
48,plus_1_put_volume,int64,Trading volume for plus_1 put option
49,plus_1_put_vwap,float64,Volume-weighted average price for plus_1 put o...
50,plus_1_put_prev_open,float64,Previous day open for plus_1 put option
51,plus_1_put_prev_close,float64,Previous day close for plus_1 put option
52,plus_1_put_prev_volume,float64,Previous day volume for plus_1 put option
53,plus_1_put_prev_vwap,float64,Previous day vwap for plus_1 put option
54,plus_2_strike,int64,Strike price for plus_2
55,plus_2_call_ticker,object,Option ticker symbol for plus_2 call
56,plus_2_call_open,float64,Open price for plus_2 call option
57,plus_2_call_high,float64,High price for plus_2 call option
58,plus_2_call_low,float64,Low price for plus_2 call option
59,plus_2_call_close,float64,Close price for plus_2 call option
60,plus_2_call_volume,float64,Trading volume for plus_2 call option
61,plus_2_call_vwap,float64,Volume-weighted average price for plus_2 call ...
62,plus_2_call_prev_open,float64,Previous day open for plus_2 call option
63,plus_2_call_prev_close,float64,Previous day close for plus_2 call option
64,plus_2_call_prev_volume,float64,Previous day volume for plus_2 call option
65,plus_2_call_prev_vwap,float64,Previous day vwap for plus_2 call option
66,plus_2_put_ticker,object,Option ticker symbol for plus_2 put
67,plus_2_put_open,float64,Open price for plus_2 put option
68,plus_2_put_high,float64,High price for plus_2 put option
69,plus_2_put_low,float64,Low price for plus_2 put option
70,plus_2_put_close,float64,Close price for plus_2 put option
71,plus_2_put_volume,float64,Trading volume for plus_2 put option
72,plus_2_put_vwap,float64,Volume-weighted average price for plus_2 put o...
73,plus_2_put_prev_open,float64,Previous day open for plus_2 put option
74,plus_2_put_prev_close,float64,Previous day close for plus_2 put option
75,plus_2_put_prev_volume,float64,Previous day volume for plus_2 put option
76,plus_2_put_prev_vwap,float64,Previous day vwap for plus_2 put option
77,plus_3_strike,int64,Strike price for plus_3
78,plus_3_call_ticker,object,Option ticker symbol for plus_3 call
79,plus_3_call_open,float64,Open price for plus_3 call option
80,plus_3_call_high,float64,High price for plus_3 call option
81,plus_3_call_low,float64,Low price for plus_3 call option
82,plus_3_call_close,float64,Close price for plus_3 call option
83,plus_3_call_volume,float64,Trading volume for plus_3 call option
84,plus_3_call_vwap,float64,Volume-weighted average price for plus_3 call ...
85,plus_3_call_prev_open,float64,Previous day open for plus_3 call option
86,plus_3_call_prev_close,float64,Previous day close for plus_3 call option
87,plus_3_call_prev_volume,float64,Previous day volume for plus_3 call option
88,plus_3_call_prev_vwap,float64,Previous day vwap for plus_3 call option
89,plus_3_put_ticker,object,Option ticker symbol for plus_3 put
90,plus_3_put_open,float64,Open price for plus_3 put option
91,plus_3_put_high,float64,High price for plus_3 put option
92,plus_3_put_low,float64,Low price for plus_3 put option
93,plus_3_put_close,float64,Close price for plus_3 put option
94,plus_3_put_volume,float64,Trading volume for plus_3 put option
95,plus_3_put_vwap,float64,Volume-weighted average price for plus_3 put o...
96,plus_3_put_prev_open,float64,Previous day open for plus_3 put option
97,plus_3_put_prev_close,float64,Previous day close for plus_3 put option
98,plus_3_put_prev_volume,float64,Previous day volume for plus_3 put option
99,plus_3_put_prev_vwap,float64,Previous day vwap for plus_3 put option
100,plus_4_strike,int64,Strike price for plus_4
101,plus_4_call_ticker,object,Option ticker symbol for plus_4 call
102,plus_4_call_open,float64,Open price for plus_4 call option
103,plus_4_call_high,float64,High price for plus_4 call option
104,plus_4_call_low,float64,Low price for plus_4 call option
105,plus_4_call_close,float64,Close price for plus_4 call option
106,plus_4_call_volume,float64,Trading volume for plus_4 call option
107,plus_4_call_vwap,float64,Volume-weighted average price for plus_4 call ...
108,plus_4_call_prev_open,float64,Previous day open for plus_4 call option
109,plus_4_call_prev_close,float64,Previous day close for plus_4 call option
110,plus_4_call_prev_volume,float64,Previous day volume for plus_4 call option
111,plus_4_call_prev_vwap,float64,Previous day vwap for plus_4 call option
112,plus_4_put_ticker,object,Option ticker symbol for plus_4 put
113,plus_4_put_open,float64,Open price for plus_4 put option
114,plus_4_put_high,float64,High price for plus_4 put option
115,plus_4_put_low,float64,Low price for plus_4 put option
116,plus_4_put_close,float64,Close price for plus_4 put option
117,plus_4_put_volume,float64,Trading volume for plus_4 put option
118,plus_4_put_vwap,float64,Volume-weighted average price for plus_4 put o...
119,plus_4_put_prev_open,float64,Previous day open for plus_4 put option
120,plus_4_put_prev_close,float64,Previous day close for plus_4 put option
121,plus_4_put_prev_volume,float64,Previous day volume for plus_4 put option
122,plus_4_put_prev_vwap,float64,Previous day vwap for plus_4 put option
123,plus_5_strike,int64,Strike price for plus_5
124,plus_5_call_ticker,object,Option ticker symbol for plus_5 call
125,plus_5_call_open,float64,Open price for plus_5 call option
126,plus_5_call_high,float64,High price for plus_5 call option
127,plus_5_call_low,float64,Low price for plus_5 call option
128,plus_5_call_close,float64,Close price for plus_5 call option
129,plus_5_call_volume,float64,Trading volume for plus_5 call option
130,plus_5_call_vwap,float64,Volume-weighted average price for plus_5 call ...
131,plus_5_call_prev_open,float64,Previous day open for plus_5 call option
132,plus_5_call_prev_close,float64,Previous day close for plus_5 call option
133,plus_5_call_prev_volume,float64,Previous day volume for plus_5 call option
134,plus_5_call_prev_vwap,float64,Previous day vwap for plus_5 call option
135,plus_5_put_ticker,object,Option ticker symbol for plus_5 put
136,plus_5_put_open,float64,Open price for plus_5 put option
137,plus_5_put_high,float64,High price for plus_5 put option
138,plus_5_put_low,float64,Low price for plus_5 put option
139,plus_5_put_close,float64,Close price for plus_5 put option
140,plus_5_put_volume,float64,Trading volume for plus_5 put option
141,plus_5_put_vwap,float64,Volume-weighted average price for plus_5 put o...
142,plus_5_put_prev_open,float64,Previous day open for plus_5 put option
143,plus_5_put_prev_close,float64,Previous day close for plus_5 put option
144,plus_5_put_prev_volume,float64,Previous day volume for plus_5 put option
145,plus_5_put_prev_vwap,float64,Previous day vwap for plus_5 put option
146,minus_1_strike,int64,Strike price for minus_1
147,minus_1_call_ticker,object,Option ticker symbol for minus_1 call
148,minus_1_call_open,float64,Open price for minus_1 call option
149,minus_1_call_high,float64,High price for minus_1 call option
150,minus_1_call_low,float64,Low price for minus_1 call option
151,minus_1_call_close,float64,Close price for minus_1 call option
152,minus_1_call_volume,int64,Trading volume for minus_1 call option
153,minus_1_call_vwap,float64,Volume-weighted average price for minus_1 call...
154,minus_1_call_prev_open,float64,Previous day open for minus_1 call option
155,minus_1_call_prev_close,float64,Previous day close for minus_1 call option
156,minus_1_call_prev_volume,int64,Previous day volume for minus_1 call option
157,minus_1_call_prev_vwap,float64,Previous day vwap for minus_1 call option
158,minus_1_put_ticker,object,Option ticker symbol for minus_1 put
159,minus_1_put_open,float64,Open price for minus_1 put option
160,minus_1_put_high,float64,High price for minus_1 put option
161,minus_1_put_low,float64,Low price for minus_1 put option
162,minus_1_put_close,float64,Close price for minus_1 put option
163,minus_1_put_volume,int64,Trading volume for minus_1 put option
164,minus_1_put_vwap,float64,Volume-weighted average price for minus_1 put ...
165,minus_1_put_prev_open,float64,Previous day open for minus_1 put option
166,minus_1_put_prev_close,float64,Previous day close for minus_1 put option
167,minus_1_put_prev_volume,int64,Previous day volume for minus_1 put option
168,minus_1_put_prev_vwap,float64,Previous day vwap for minus_1 put option
169,minus_2_strike,int64,Strike price for minus_2
170,minus_2_call_ticker,object,Option ticker symbol for minus_2 call
171,minus_2_call_open,float64,Open price for minus_2 call option
172,minus_2_call_high,float64,High price for minus_2 call option
173,minus_2_call_low,float64,Low price for minus_2 call option
174,minus_2_call_close,float64,Close price for minus_2 call option
175,minus_2_call_volume,int64,Trading volume for minus_2 call option
176,minus_2_call_vwap,float64,Volume-weighted average price for minus_2 call...
177,minus_2_call_prev_open,float64,Previous day open for minus_2 call option
178,minus_2_call_prev_close,float64,Previous day close for minus_2 call option
179,minus_2_call_prev_volume,int64,Previous day volume for minus_2 call option
180,minus_2_call_prev_vwap,float64,Previous day vwap for minus_2 call option
181,minus_2_put_ticker,object,Option ticker symbol for minus_2 put
182,minus_2_put_open,float64,Open price for minus_2 put option
183,minus_2_put_high,float64,High price for minus_2 put option
184,minus_2_put_low,float64,Low price for minus_2 put option
185,minus_2_put_close,float64,Close price for minus_2 put option
186,minus_2_put_volume,int64,Trading volume for minus_2 put option
187,minus_2_put_vwap,float64,Volume-weighted average price for minus_2 put ...
188,minus_2_put_prev_open,float64,Previous day open for minus_2 put option
189,minus_2_put_prev_close,float64,Previous day close for minus_2 put option
190,minus_2_put_prev_volume,int64,Previous day volume for minus_2 put option
191,minus_2_put_prev_vwap,float64,Previous day vwap for minus_2 put option
192,minus_3_strike,int64,Strike price for minus_3
193,minus_3_call_ticker,object,Option ticker symbol for minus_3 call
194,minus_3_call_open,float64,Open price for minus_3 call option
195,minus_3_call_high,float64,High price for minus_3 call option
196,minus_3_call_low,float64,Low price for minus_3 call option
197,minus_3_call_close,float64,Close price for minus_3 call option
198,minus_3_call_volume,int64,Trading volume for minus_3 call option
199,minus_3_call_vwap,float64,Volume-weighted average price for minus_3 call...
200,minus_3_call_prev_open,float64,Previous day open for minus_3 call option
201,minus_3_call_prev_close,float64,Previous day close for minus_3 call option
202,minus_3_call_prev_volume,int64,Previous day volume for minus_3 call option
203,minus_3_call_prev_vwap,float64,Previous day vwap for minus_3 call option
204,minus_3_put_ticker,object,Option ticker symbol for minus_3 put
205,minus_3_put_open,float64,Open price for minus_3 put option
206,minus_3_put_high,float64,High price for minus_3 put option
207,minus_3_put_low,float64,Low price for minus_3 put option
208,minus_3_put_close,float64,Close price for minus_3 put option
209,minus_3_put_volume,int64,Trading volume for minus_3 put option
210,minus_3_put_vwap,float64,Volume-weighted average price for minus_3 put ...
211,minus_3_put_prev_open,float64,Previous day open for minus_3 put option
212,minus_3_put_prev_close,float64,Previous day close for minus_3 put option
213,minus_3_put_prev_volume,int64,Previous day volume for minus_3 put option
214,minus_3_put_prev_vwap,float64,Previous day vwap for minus_3 put option

In [9]:
df

,Column,Type,Description
0,date,object,Trading date in YYYY-MM-DD format
1,spy_open,float64,SPY opening price for the day
2,spy_high,float64,SPY highest price for the day
3,spy_low,float64,SPY lowest price for the day
4,spy_close,float64,SPY closing price for the day
5,spy_close_prev_day,float64,SPY previous day closing price
6,spy_volume,float64,SPY trading volume for the day
7,expiration_date,object,Option expiration date
8,atm_strike,int64,Strike price for atm
9,atm_call_ticker,object,Option ticker symbol for atm call
10,atm_call_open,float64,Open price for atm call option
11,atm_call_high,float64,High price for atm call option
12,atm_call_low,float64,Low price for atm call option
13,atm_call_close,float64,Close price for atm call option
14,atm_call_volume,int64,Trading volume for atm call option
15,atm_call_vwap,float64,Volume-weighted average price for atm call option
16,atm_call_prev_open,float64,Previous day open for atm call option
17,atm_call_prev_close,float64,Previous day close for atm call option
18,atm_call_prev_volume,int64,Previous day volume for atm call option
19,atm_call_prev_vwap,float64,Previous day vwap for atm call option
20,atm_put_ticker,object,Option ticker symbol for atm put
21,atm_put_open,float64,Open price for atm put option
22,atm_put_high,float64,High price for atm put option
23,atm_put_low,float64,Low price for atm put option
24,atm_put_close,float64,Close price for atm put option
25,atm_put_volume,int64,Trading volume for atm put option
26,atm_put_vwap,float64,Volume-weighted average price for atm put option
27,atm_put_prev_open,float64,Previous day open for atm put option
28,atm_put_prev_close,float64,Previous day close for atm put option
29,atm_put_prev_volume,int64,Previous day volume for atm put option
30,atm_put_prev_vwap,float64,Previous day vwap for atm put option
31,plus_1_strike,int64,Strike price for plus_1
32,plus_1_call_ticker,object,Option ticker symbol for plus_1 call
33,plus_1_call_open,float64,Open price for plus_1 call option
34,plus_1_call_high,float64,High price for plus_1 call option
35,plus_1_call_low,float64,Low price for plus_1 call option
36,plus_1_call_close,float64,Close price for plus_1 call option
37,plus_1_call_volume,int64,Trading volume for plus_1 call option
38,plus_1_call_vwap,float64,Volume-weighted average price for plus_1 call ...
39,plus_1_call_prev_open,float64,Previous day open for plus_1 call option
40,plus_1_call_prev_close,float64,Previous day close for plus_1 call option
41,plus_1_call_prev_volume,float64,Previous day volume for plus_1 call option
42,plus_1_call_prev_vwap,float64,Previous day vwap for plus_1 call option
43,plus_1_put_ticker,object,Option ticker symbol for plus_1 put
44,plus_1_put_open,float64,Open price for plus_1 put option
45,plus_1_put_high,float64,High price for plus_1 put option
46,plus_1_put_low,float64,Low price for plus_1 put option
47,plus_1_put_close,float64,Close price for plus_1 put option
48,plus_1_put_volume,int64,Trading volume for plus_1 put option
49,plus_1_put_vwap,float64,Volume-weighted average price for plus_1 put o...
50,plus_1_put_prev_open,float64,Previous day open for plus_1 put option
51,plus_1_put_prev_close,float64,Previous day close for plus_1 put option
52,plus_1_put_prev_volume,float64,Previous day volume for plus_1 put option
53,plus_1_put_prev_vwap,float64,Previous day vwap for plus_1 put option
54,plus_2_strike,int64,Strike price for plus_2
55,plus_2_call_ticker,object,Option ticker symbol for plus_2 call
56,plus_2_call_open,float64,Open price for plus_2 call option
57,plus_2_call_high,float64,High price for plus_2 call option
58,plus_2_call_low,float64,Low price for plus_2 call option
59,plus_2_call_close,float64,Close price for plus_2 call option
60,plus_2_call_volume,float64,Trading volume for plus_2 call option
61,plus_2_call_vwap,float64,Volume-weighted average price for plus_2 call ...
62,plus_2_call_prev_open,float64,Previous day open for plus_2 call option
63,plus_2_call_prev_close,float64,Previous day close for plus_2 call option
64,plus_2_call_prev_volume,float64,Previous day volume for plus_2 call option
65,plus_2_call_prev_vwap,float64,Previous day vwap for plus_2 call option
66,plus_2_put_ticker,object,Option ticker symbol for plus_2 put
67,plus_2_put_open,float64,Open price for plus_2 put option
68,plus_2_put_high,float64,High price for plus_2 put option
69,plus_2_put_low,float64,Low price for plus_2 put option
70,plus_2_put_close,float64,Close price for plus_2 put option
71,plus_2_put_volume,float64,Trading volume for plus_2 put option
72,plus_2_put_vwap,float64,Volume-weighted average price for plus_2 put o...
73,plus_2_put_prev_open,float64,Previous day open for plus_2 put option
74,plus_2_put_prev_close,float64,Previous day close for plus_2 put option
75,plus_2_put_prev_volume,float64,Previous day volume for plus_2 put option
76,plus_2_put_prev_vwap,float64,Previous day vwap for plus_2 put option
77,plus_3_strike,int64,Strike price for plus_3
78,plus_3_call_ticker,object,Option ticker symbol for plus_3 call
79,plus_3_call_open,float64,Open price for plus_3 call option
80,plus_3_call_high,float64,High price for plus_3 call option
81,plus_3_call_low,float64,Low price for plus_3 call option
82,plus_3_call_close,float64,Close price for plus_3 call option
83,plus_3_call_volume,float64,Trading volume for plus_3 call option
84,plus_3_call_vwap,float64,Volume-weighted average price for plus_3 call ...
85,plus_3_call_prev_open,float64,Previous day open for plus_3 call option
86,plus_3_call_prev_close,float64,Previous day close for plus_3 call option
87,plus_3_call_prev_volume,float64,Previous day volume for plus_3 call option
88,plus_3_call_prev_vwap,float64,Previous day vwap for plus_3 call option
89,plus_3_put_ticker,object,Option ticker symbol for plus_3 put
90,plus_3_put_open,float64,Open price for plus_3 put option
91,plus_3_put_high,float64,High price for plus_3 put option
92,plus_3_put_low,float64,Low price for plus_3 put option
93,plus_3_put_close,float64,Close price for plus_3 put option
94,plus_3_put_volume,float64,Trading volume for plus_3 put option
95,plus_3_put_vwap,float64,Volume-weighted average price for plus_3 put o...
96,plus_3_put_prev_open,float64,Previous day open for plus_3 put option
97,plus_3_put_prev_close,float64,Previous day close for plus_3 put option
98,plus_3_put_prev_volume,float64,Previous day volume for plus_3 put option
99,plus_3_put_prev_vwap,float64,Previous day vwap for plus_3 put option
100,plus_4_strike,int64,Strike price for plus_4
101,plus_4_call_ticker,object,Option ticker symbol for plus_4 call
102,plus_4_call_open,float64,Open price for plus_4 call option
103,plus_4_call_high,float64,High price for plus_4 call option
104,plus_4_call_low,float64,Low price for plus_4 call option
105,plus_4_call_close,float64,Close price for plus_4 call option
106,plus_4_call_volume,float64,Trading volume for plus_4 call option
107,plus_4_call_vwap,float64,Volume-weighted average price for plus_4 call ...
108,plus_4_call_prev_open,float64,Previous day open for plus_4 call option
109,plus_4_call_prev_close,float64,Previous day close for plus_4 call option
110,plus_4_call_prev_volume,float64,Previous day volume for plus_4 call option
111,plus_4_call_prev_vwap,float64,Previous day vwap for plus_4 call option
112,plus_4_put_ticker,object,Option ticker symbol for plus_4 put
113,plus_4_put_open,float64,Open price for plus_4 put option
114,plus_4_put_high,float64,High price for plus_4 put option
115,plus_4_put_low,float64,Low price for plus_4 put option
116,plus_4_put_close,float64,Close price for plus_4 put option
117,plus_4_put_volume,float64,Trading volume for plus_4 put option
118,plus_4_put_vwap,float64,Volume-weighted average price for plus_4 put o...
119,plus_4_put_prev_open,float64,Previous day open for plus_4 put option
120,plus_4_put_prev_close,float64,Previous day close for plus_4 put option
121,plus_4_put_prev_volume,float64,Previous day volume for plus_4 put option
122,plus_4_put_prev_vwap,float64,Previous day vwap for plus_4 put option
123,plus_5_strike,int64,Strike price for plus_5
124,plus_5_call_ticker,object,Option ticker symbol for plus_5 call
125,plus_5_call_open,float64,Open price for plus_5 call option
126,plus_5_call_high,float64,High price for plus_5 call option
127,plus_5_call_low,float64,Low price for plus_5 call option
128,plus_5_call_close,float64,Close price for plus_5 call option
129,plus_5_call_volume,float64,Trading volume for plus_5 call option
130,plus_5_call_vwap,float64,Volume-weighted average price for plus_5 call ...
131,plus_5_call_prev_open,float64,Previous day open for plus_5 call option
132,plus_5_call_prev_close,float64,Previous day close for plus_5 call option
133,plus_5_call_prev_volume,float64,Previous day volume for plus_5 call option
134,plus_5_call_prev_vwap,float64,Previous day vwap for plus_5 call option
135,plus_5_put_ticker,object,Option ticker symbol for plus_5 put
136,plus_5_put_open,float64,Open price for plus_5 put option
137,plus_5_put_high,float64,High price for plus_5 put option
138,plus_5_put_low,float64,Low price for plus_5 put option
139,plus_5_put_close,float64,Close price for plus_5 put option
140,plus_5_put_volume,float64,Trading volume for plus_5 put option
141,plus_5_put_vwap,float64,Volume-weighted average price for plus_5 put o...
142,plus_5_put_prev_open,float64,Previous day open for plus_5 put option
143,plus_5_put_prev_close,float64,Previous day close for plus_5 put option
144,plus_5_put_prev_volume,float64,Previous day volume for plus_5 put option
145,plus_5_put_prev_vwap,float64,Previous day vwap for plus_5 put option
146,minus_1_strike,int64,Strike price for minus_1
147,minus_1_call_ticker,object,Option ticker symbol for minus_1 call
148,minus_1_call_open,float64,Open price for minus_1 call option
149,minus_1_call_high,float64,High price for minus_1 call option
150,minus_1_call_low,float64,Low price for minus_1 call option
151,minus_1_call_close,float64,Close price for minus_1 call option
152,minus_1_call_volume,int64,Trading volume for minus_1 call option
153,minus_1_call_vwap,float64,Volume-weighted average price for minus_1 call...
154,minus_1_call_prev_open,float64,Previous day open for minus_1 call option
155,minus_1_call_prev_close,float64,Previous day close for minus_1 call option
156,minus_1_call_prev_volume,int64,Previous day volume for minus_1 call option
157,minus_1_call_prev_vwap,float64,Previous day vwap for minus_1 call option
158,minus_1_put_ticker,object,Option ticker symbol for minus_1 put
159,minus_1_put_open,float64,Open price for minus_1 put option
160,minus_1_put_high,float64,High price for minus_1 put option
161,minus_1_put_low,float64,Low price for minus_1 put option
162,minus_1_put_close,float64,Close price for minus_1 put option
163,minus_1_put_volume,int64,Trading volume for minus_1 put option
164,minus_1_put_vwap,float64,Volume-weighted average price for minus_1 put ...
165,minus_1_put_prev_open,float64,Previous day open for minus_1 put option
166,minus_1_put_prev_close,float64,Previous day close for minus_1 put option
167,minus_1_put_prev_volume,int64,Previous day volume for minus_1 put option
168,minus_1_put_prev_vwap,float64,Previous day vwap for minus_1 put option
169,minus_2_strike,int64,Strike price for minus_2
170,minus_2_call_ticker,object,Option ticker symbol for minus_2 call
171,minus_2_call_open,float64,Open price for minus_2 call option
172,minus_2_call_high,float64,High price for minus_2 call option
173,minus_2_call_low,float64,Low price for minus_2 call option
174,minus_2_call_close,float64,Close price for minus_2 call option
175,minus_2_call_volume,int64,Trading volume for minus_2 call option
176,minus_2_call_vwap,float64,Volume-weighted average price for minus_2 call...
177,minus_2_call_prev_open,float64,Previous day open for minus_2 call option
178,minus_2_call_prev_close,float64,Previous day close for minus_2 call option
179,minus_2_call_prev_volume,int64,Previous day volume for minus_2 call option
180,minus_2_call_prev_vwap,float64,Previous day vwap for minus_2 call option
181,minus_2_put_ticker,object,Option ticker symbol for minus_2 put
182,minus_2_put_open,float64,Open price for minus_2 put option
183,minus_2_put_high,float64,High price for minus_2 put option
184,minus_2_put_low,float64,Low price for minus_2 put option
185,minus_2_put_close,float64,Close price for minus_2 put option
186,minus_2_put_volume,int64,Trading volume for minus_2 put option
187,minus_2_put_vwap,float64,Volume-weighted average price for minus_2 put ...
188,minus_2_put_prev_open,float64,Previous day open for minus_2 put option
189,minus_2_put_prev_close,float64,Previous day close for minus_2 put option
190,minus_2_put_prev_volume,int64,Previous day volume for minus_2 put option
191,minus_2_put_prev_vwap,float64,Previous day vwap for minus_2 put option
192,minus_3_strike,int64,Strike price for minus_3
193,minus_3_call_ticker,object,Option ticker symbol for minus_3 call
194,minus_3_call_open,float64,Open price for minus_3 call option
195,minus_3_call_high,float64,High price for minus_3 call option
196,minus_3_call_low,float64,Low price for minus_3 call option
197,minus_3_call_close,float64,Close price for minus_3 call option
198,minus_3_call_volume,int64,Trading volume for minus_3 call option
199,minus_3_call_vwap,float64,Volume-weighted average price for minus_3 call...
200,minus_3_call_prev_open,float64,Previous day open for minus_3 call option
201,minus_3_call_prev_close,float64,Previous day close for minus_3 call option
202,minus_3_call_prev_volume,int64,Previous day volume for minus_3 call option
203,minus_3_call_prev_vwap,float64,Previous day vwap for minus_3 call option
204,minus_3_put_ticker,object,Option ticker symbol for minus_3 put
205,minus_3_put_open,float64,Open price for minus_3 put option
206,minus_3_put_high,float64,High price for minus_3 put option
207,minus_3_put_low,float64,Low price for minus_3 put option
208,minus_3_put_close,float64,Close price for minus_3 put option
209,minus_3_put_volume,int64,Trading volume for minus_3 put option
210,minus_3_put_vwap,float64,Volume-weighted average price for minus_3 put ...
211,minus_3_put_prev_open,float64,Previous day open for minus_3 put option
212,minus_3_put_prev_close,float64,Previous day close for minus_3 put option
213,minus_3_put_prev_volume,int64,Previous day volume for minus_3 put option
214,minus_3_put_prev_vwap,float64,Previous day vwap for minus_3 put option

In [18]:
df.loc[:, :]

,date,spy_open,spy_high,spy_low,spy_close,spy_close_prev_day,spy_volume,expiration_date,atm_strike,atm_call_ticker,...,minus_3_put_open,minus_3_put_high,minus_3_put_low,minus_3_put_close,minus_3_put_volume,minus_3_put_vwap,minus_3_put_prev_open,minus_3_put_prev_close,minus_3_put_prev_volume,minus_3_put_prev_vwap
0,2023-09-05,450.73,451.06,449.1700,449.24,451.19,54634810.0,2023-09-05,451,O:SPY230905C00451000,...,0.03,0.06,0.01,0.01,28645,0.0325,0.12,0.06,19408,0.1099
1,2023-09-06,448.40,448.51,443.8100,446.22,449.24,70758512.0,2023-09-06,449,O:SPY230906C00449000,...,0.04,0.37,0.01,0.01,151628,0.1075,0.09,0.04,6547,0.0551
2,2023-09-07,443.11,445.55,442.7500,444.85,446.22,70348426.0,2023-09-07,446,O:SPY230907C00446000,...,0.21,0.25,0.01,0.01,89253,0.1054,0.06,0.05,16499,0.1151
3,2023-09-08,444.90,447.11,444.5300,445.52,444.85,62068437.0,2023-09-08,445,O:SPY230908C00445000,...,0.04,0.04,0.01,0.01,6566,0.0151,0.39,0.06,19809,0.1725
4,2023-09-11,448.24,448.77,446.4699,448.45,445.52,59977618.0,2023-09-11,446,O:SPY230911C00446000,...,0.01,0.06,0.01,0.01,13771,0.0101,0.28,0.07,22475,0.1060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,2025-08-25,644.04,645.29,642.3500,642.47,645.31,51274332.0,2025-08-25,645,O:SPY250825C00645000,...,0.11,0.18,0.01,0.01,37627,0.0629,3.74,0.17,24617,1.2929
495,2025-08-26,642.20,645.51,641.5700,645.16,642.47,51581565.0,2025-08-26,642,O:SPY250826C00642000,...,0.07,0.11,0.01,0.01,22423,0.0519,0.20,0.12,5989,0.1064
496,2025-08-27,644.57,647.37,644.4200,646.63,645.16,48341069.0,2025-08-27,645,O:SPY250827C00645000,...,0.24,0.26,0.01,0.02,22813,0.1017,1.24,0.23,14644,0.6639
497,2025-08-28,647.24,649.48,645.3400,648.92,646.63,61519461.0,2025-08-28,647,O:SPY250828C00647000,...,0.07,0.22,0.01,0.01,27065,0.0758,1.23,0.72,8356,0.8511
498,2025-08-29,647.47,647.84,643.1400,645.05,648.92,74522192.0,2025-08-29,649,O:SPY250829C00649000,...,0.22,1.21,0.01,0.01,339865,0.5441,0.55,0.30,25765,0.5050

In [16]:
df= pd.read_csv('spy_wide_strikes_default_2023-09-01_to_2025-08-30.csv')

In [17]:
df_schema= pd.read_csv('spy_wide_strikes_default_2023-09-01_to_2025-08-30_schema.csv')

In [20]:
atm_open = df.loc[:,'atm_call_open']

In [21]:
atm_close = df.loc[:, 'atm_call_close']

In [22]:
print(atm_open.mean(), atm_close.mean())

2.0202204408817637 2.0464529058116234