In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('spy_options_default_grouping_2024-12-28_to_2025-08-28.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 98 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 165 non-null    object
 1   spy_open             165 non-null    float64
 2   spy_high             165 non-null    float64
 3   spy_low              165 non-null    float64
 4   spy_close            165 non-null    float64
 5   spy_close_prev_day   165 non-null    float64
 6   spy_volume           165 non-null    float64
 7   expiration_date      165 non-null    object
 8   atm_strike           165 non-null    int64
 9   atm_call_ticker      165 non-null    object
 10  atm_call_open        165 non-null    float64
 11  atm_call_high        165 non-null    float64
 12  atm_call_low         165 non-null    float64
 13  atm_call_close       165 non-null    float64
 14  atm_call_volume      165 non-null    int64
 15  atm_call_vwap        165 non-null    float64
 16  atm_put_ticker       165 non-null    object
 17  atm_put_open         165 non-null    float64
 18  atm_put_high         165 non-null    float64
 19  atm_put_low          165 non-null    float64
 20  atm_put_close        165 non-null    float64
 21  atm_put_volume       165 non-null    int64
 22  atm_put_vwap         165 non-null    float64
 23  plus_1_strike        165 non-null    int64
 24  plus_1_call_ticker   165 non-null    object
 25  plus_1_call_open     165 non-null    float64
 26  plus_1_call_high     165 non-null    float64
 27  plus_1_call_low      165 non-null    float64
 28  plus_1_call_close    165 non-null    float64
 29  plus_1_call_volume   165 non-null    int64
 30  plus_1_call_vwap     165 non-null    float64
 31  plus_1_put_ticker    165 non-null    object
 32  plus_1_put_open      165 non-null    float64
 33  plus_1_put_high      165 non-null    float64
 34  plus_1_put_low       165 non-null    float64
 35  plus_1_put_close     165 non-null    float64
 36  plus_1_put_volume    165 non-null    int64
 37  plus_1_put_vwap      165 non-null    float64
 38  plus_2_strike        165 non-null    int64
 39  plus_2_call_ticker   165 non-null    object
 40  plus_2_call_open     165 non-null    float64
 41  plus_2_call_high     165 non-null    float64
 42  plus_2_call_low      165 non-null    float64
 43  plus_2_call_close    165 non-null    float64
 44  plus_2_call_volume   165 non-null    int64
 45  plus_2_call_vwap     165 non-null    float64
 46  plus_2_put_ticker    165 non-null    object
 47  plus_2_put_open      165 non-null    float64
 48  plus_2_put_high      165 non-null    float64
 49  plus_2_put_low       165 non-null    float64
 50  plus_2_put_close     165 non-null    float64
 51  plus_2_put_volume    165 non-null    int64
 52  plus_2_put_vwap      165 non-null    float64
 53  plus_3_strike        165 non-null    int64
 54  plus_3_call_ticker   165 non-null    object
 55  plus_3_call_open     165 non-null    float64
 56  plus_3_call_high     165 non-null    float64
 57  plus_3_call_low      165 non-null    float64
 58  plus_3_call_close    165 non-null    float64
 59  plus_3_call_volume   165 non-null    int64
 60  plus_3_call_vwap     165 non-null    float64
 61  plus_3_put_ticker    165 non-null    object
 62  plus_3_put_open      165 non-null    float64
 63  plus_3_put_high      165 non-null    float64
 64  plus_3_put_low       165 non-null    float64
 65  plus_3_put_close     165 non-null    float64
 66  plus_3_put_volume    165 non-null    int64
 67  plus_3_put_vwap      165 non-null    float64
 68  minus_1_strike       165 non-null    int64
 69  minus_1_call_ticker  165 non-null    object
 70  minus_1_call_open    165 non-null    float64
 71  minus_1_call_high    165 non-null    float64
 72  minus_1_call_low     165 non-null    float64
 73  minus_1_call_close   165 non-null    float64
 74  minus_1_call_volume  165 non-null    int64
 75  minus_1_call_vwap    165 non-null    float64
 76  minus_1_put_ticker   165 non-null    object
 77  minus_1_put_open     165 non-null    float64
 78  minus_1_put_high     165 non-null    float64
 79  minus_1_put_low      165 non-null    float64
 80  minus_1_put_close    165 non-null    float64
 81  minus_1_put_volume   165 non-null    int64
 82  minus_1_put_vwap     165 non-null    float64
 83  minus_2_strike       165 non-null    int64
 84  minus_2_call_ticker  165 non-null    object
 85  minus_2_call_open    165 non-null    float64
 86  minus_2_call_high    165 non-null    float64
 87  minus_2_call_low     165 non-null    float64
 88  minus_2_call_close   165 non-null    float64
 89  minus_2_call_volume  165 non-null    int64
 90  minus_2_call_vwap    165 non-null    float64
 91  minus_2_put_ticker   165 non-null    object
 92  minus_2_put_open     165 non-null    float64
 93  minus_2_put_high     165 non-null    float64
 94  minus_2_put_low      165 non-null    float64
 95  minus_2_put_close    165 non-null    float64
 96  minus_2_put_volume   165 non-null    int64
 97  minus_2_put_vwap     165 non-null    float64
dtypes: float64(66), int64(18), object(14)
memory usage: 126.5+ KB

In [4]:
df

,date,spy_open,spy_high,spy_low,spy_close,spy_close_prev_day,spy_volume,expiration_date,atm_strike,atm_call_ticker,...,minus_2_call_close,minus_2_call_volume,minus_2_call_vwap,minus_2_put_ticker,minus_2_put_open,minus_2_put_high,minus_2_put_low,minus_2_put_close,minus_2_put_volume,minus_2_put_vwap
0,2024-12-31,589.905,590.6399,584.42,586.08,588.22,57052654.0,2024-12-31,588,O:SPY241231C00588000,...,0.39,226714,1.0956,O:SPY241231P00586000,0.73,2.04,0.02,0.03,327059,1.0635
1,2025-01-02,589.390,591.1300,580.50,584.64,586.08,50079975.0,2025-01-02,586,O:SPY250102C00586000,...,1.01,182292,0.8078,O:SPY250102P00584000,0.45,3.75,0.01,0.02,206059,0.8623
2,2025-01-03,587.530,592.6000,586.43,591.95,584.64,37868659.0,2025-01-03,585,O:SPY250103C00585000,...,8.63,4579,6.0792,O:SPY250103P00583000,0.54,0.64,0.01,0.01,78346,0.2412
3,2025-01-06,596.270,599.7000,593.60,595.36,591.95,47123442.0,2025-01-06,592,O:SPY250106C00592000,...,5.75,8133,7.1239,O:SPY250106P00590000,0.19,0.22,0.01,0.01,82690,0.0582
4,2025-01-07,597.420,597.7500,586.78,588.63,595.36,60205552.0,2025-01-07,595,O:SPY250107C00595000,...,0.01,327027,0.8209,O:SPY250107P00593000,0.29,6.14,0.24,4.00,206826,1.4293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,2025-08-22,637.760,646.5000,637.25,645.31,635.55,84083214.0,2025-08-22,636,O:SPY250822C00636000,...,11.52,7912,7.2885,O:SPY250822P00634000,1.25,1.42,0.01,0.01,49582,0.4151
161,2025-08-25,644.040,645.2900,642.35,642.47,645.31,51274332.0,2025-08-25,645,O:SPY250825C00645000,...,0.06,121897,1.2100,O:SPY250825P00643000,0.63,0.91,0.04,0.12,440295,0.2702
162,2025-08-26,642.200,645.5100,641.57,645.16,642.47,51581565.0,2025-08-26,642,O:SPY250826C00642000,...,5.61,13089,2.9870,O:SPY250826P00640000,0.42,0.55,0.01,0.01,177959,0.1829
163,2025-08-27,644.570,647.3700,644.42,646.63,645.16,48341069.0,2025-08-27,645,O:SPY250827C00645000,...,3.75,22753,3.5640,O:SPY250827P00643000,0.95,0.98,0.13,0.20,142987,0.4718
164,2025-08-28,647.240,649.4800,645.34,648.92,646.63,61532230.0,2025-08-28,647,O:SPY250828C00647000,...,3.90,47813,2.2974,O:SPY250828P00645000,0.42,2.28,0.01,0.01,276548,0.4404

In [5]:
df2= pd.read_csv('spy_options_snapshots_20250822_to_20250829.csv')

In [6]:
df2.shape

(59276, 29)

In [7]:
df2

,date,ticker,contract_type,exercise_style,expiration_date,shares_per_contract,strike_price,day_change,day_change_percent,day_close,...,theta,vega,implied_volatility,break_even_price,open_interest,underlying_ticker,underlying_price,underlying_change_to_break_even,underlying_last_updated,underlying_timeframe
0,2025-08-18,O:SPY250829C00315000,call,american,2025-08-29,100,315.0,-0.88,-0.266,329.71,...,NaN,NaN,NaN,NaN,270,SPY,NaN,NaN,NaN,NaN
1,2025-08-18,O:SPY250829C00320000,call,american,2025-08-29,100,320.0,3.69,1.151,324.19,...,NaN,NaN,NaN,NaN,215,SPY,NaN,NaN,NaN,NaN
2,2025-08-18,O:SPY250829C00325000,call,american,2025-08-29,100,325.0,0.00,0.000,320.67,...,NaN,NaN,NaN,NaN,104,SPY,NaN,NaN,NaN,NaN
3,2025-08-18,O:SPY250829C00330000,call,american,2025-08-29,100,330.0,0.00,0.000,308.86,...,NaN,NaN,NaN,NaN,222,SPY,NaN,NaN,NaN,NaN
4,2025-08-18,O:SPY250829C00335000,call,american,2025-08-29,100,335.0,0.00,0.000,199.74,...,NaN,NaN,NaN,NaN,156,SPY,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59271,2025-08-26,O:SPY271217P00980000,put,american,2027-12-17,100,980.0,NaN,NaN,NaN,...,-0.003482,1.069587,0.268447,NaN,0,SPY,NaN,NaN,NaN,NaN
59272,2025-08-26,O:SPY271217P00985000,put,american,2027-12-17,100,985.0,NaN,NaN,NaN,...,-0.003482,1.070465,0.270951,NaN,0,SPY,NaN,NaN,NaN,NaN
59273,2025-08-26,O:SPY271217P00990000,put,american,2027-12-17,100,990.0,NaN,NaN,NaN,...,-0.003482,1.057038,0.273439,NaN,0,SPY,NaN,NaN,NaN,NaN
59274,2025-08-26,O:SPY271217P00995000,put,american,2027-12-17,100,995.0,0.00,0.000,350.09,...,-0.005357,1.070661,0.276898,NaN,0,SPY,NaN,NaN,NaN,NaN
59275,2025-08-26,O:SPY271217P01000000,put,american,2027-12-17,100,1000.0,0.00,0.000,355.06,...,-0.005357,1.071605,0.279360,NaN,0,SPY,NaN,NaN,NaN,NaN

In [8]:
df['underlying_last_update']

KeyError: 'underlying_last_update'

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 98 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 165 non-null    object
 1   spy_open             165 non-null    float64
 2   spy_high             165 non-null    float64
 3   spy_low              165 non-null    float64
 4   spy_close            165 non-null    float64
 5   spy_close_prev_day   165 non-null    float64
 6   spy_volume           165 non-null    float64
 7   expiration_date      165 non-null    object
 8   atm_strike           165 non-null    int64
 9   atm_call_ticker      165 non-null    object
 10  atm_call_open        165 non-null    float64
 11  atm_call_high        165 non-null    float64
 12  atm_call_low         165 non-null    float64
 13  atm_call_close       165 non-null    float64
 14  atm_call_volume      165 non-null    int64
 15  atm_call_vwap        165 non-null    float64
 16  atm_put_ticker       165 non-null    object
 17  atm_put_open         165 non-null    float64
 18  atm_put_high         165 non-null    float64
 19  atm_put_low          165 non-null    float64
 20  atm_put_close        165 non-null    float64
 21  atm_put_volume       165 non-null    int64
 22  atm_put_vwap         165 non-null    float64
 23  plus_1_strike        165 non-null    int64
 24  plus_1_call_ticker   165 non-null    object
 25  plus_1_call_open     165 non-null    float64
 26  plus_1_call_high     165 non-null    float64
 27  plus_1_call_low      165 non-null    float64
 28  plus_1_call_close    165 non-null    float64
 29  plus_1_call_volume   165 non-null    int64
 30  plus_1_call_vwap     165 non-null    float64
 31  plus_1_put_ticker    165 non-null    object
 32  plus_1_put_open      165 non-null    float64
 33  plus_1_put_high      165 non-null    float64
 34  plus_1_put_low       165 non-null    float64
 35  plus_1_put_close     165 non-null    float64
 36  plus_1_put_volume    165 non-null    int64
 37  plus_1_put_vwap      165 non-null    float64
 38  plus_2_strike        165 non-null    int64
 39  plus_2_call_ticker   165 non-null    object
 40  plus_2_call_open     165 non-null    float64
 41  plus_2_call_high     165 non-null    float64
 42  plus_2_call_low      165 non-null    float64
 43  plus_2_call_close    165 non-null    float64
 44  plus_2_call_volume   165 non-null    int64
 45  plus_2_call_vwap     165 non-null    float64
 46  plus_2_put_ticker    165 non-null    object
 47  plus_2_put_open      165 non-null    float64
 48  plus_2_put_high      165 non-null    float64
 49  plus_2_put_low       165 non-null    float64
 50  plus_2_put_close     165 non-null    float64
 51  plus_2_put_volume    165 non-null    int64
 52  plus_2_put_vwap      165 non-null    float64
 53  plus_3_strike        165 non-null    int64
 54  plus_3_call_ticker   165 non-null    object
 55  plus_3_call_open     165 non-null    float64
 56  plus_3_call_high     165 non-null    float64
 57  plus_3_call_low      165 non-null    float64
 58  plus_3_call_close    165 non-null    float64
 59  plus_3_call_volume   165 non-null    int64
 60  plus_3_call_vwap     165 non-null    float64
 61  plus_3_put_ticker    165 non-null    object
 62  plus_3_put_open      165 non-null    float64
 63  plus_3_put_high      165 non-null    float64
 64  plus_3_put_low       165 non-null    float64
 65  plus_3_put_close     165 non-null    float64
 66  plus_3_put_volume    165 non-null    int64
 67  plus_3_put_vwap      165 non-null    float64
 68  minus_1_strike       165 non-null    int64
 69  minus_1_call_ticker  165 non-null    object
 70  minus_1_call_open    165 non-null    float64
 71  minus_1_call_high    165 non-null    float64
 72  minus_1_call_low     165 non-null    float64
 73  minus_1_call_close   165 non-null    float64
 74  minus_1_call_volume  165 non-null    int64
 75  minus_1_call_vwap    165 non-null    float64
 76  minus_1_put_ticker   165 non-null    object
 77  minus_1_put_open     165 non-null    float64
 78  minus_1_put_high     165 non-null    float64
 79  minus_1_put_low      165 non-null    float64
 80  minus_1_put_close    165 non-null    float64
 81  minus_1_put_volume   165 non-null    int64
 82  minus_1_put_vwap     165 non-null    float64
 83  minus_2_strike       165 non-null    int64
 84  minus_2_call_ticker  165 non-null    object
 85  minus_2_call_open    165 non-null    float64
 86  minus_2_call_high    165 non-null    float64
 87  minus_2_call_low     165 non-null    float64
 88  minus_2_call_close   165 non-null    float64
 89  minus_2_call_volume  165 non-null    int64
 90  minus_2_call_vwap    165 non-null    float64
 91  minus_2_put_ticker   165 non-null    object
 92  minus_2_put_open     165 non-null    float64
 93  minus_2_put_high     165 non-null    float64
 94  minus_2_put_low      165 non-null    float64
 95  minus_2_put_close    165 non-null    float64
 96  minus_2_put_volume   165 non-null    int64
 97  minus_2_put_vwap     165 non-null    float64
dtypes: float64(66), int64(18), object(14)
memory usage: 126.5+ KB

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59276 entries, 0 to 59275
Data columns (total 29 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   date                             59276 non-null  object
 1   ticker                           59276 non-null  object
 2   contract_type                    59276 non-null  object
 3   exercise_style                   59276 non-null  object
 4   expiration_date                  59276 non-null  object
 5   shares_per_contract              59276 non-null  int64
 6   strike_price                     59276 non-null  float64
 7   day_change                       50680 non-null  float64
 8   day_change_percent               50680 non-null  float64
 9   day_close                        51408 non-null  float64
 10  day_high                         51408 non-null  float64
 11  day_low                          51408 non-null  float64
 12  day_open                         51408 non-null  float64
 13  day_previous_close               50680 non-null  float64
 14  day_volume                       51408 non-null  float64
 15  day_vwap                         51408 non-null  float64
 16  day_last_updated                 51408 non-null  float64
 17  delta                            56385 non-null  float64
 18  gamma                            56385 non-null  float64
 19  theta                            56385 non-null  float64
 20  vega                             56385 non-null  float64
 21  implied_volatility               57939 non-null  float64
 22  break_even_price                 0 non-null      float64
 23  open_interest                    59276 non-null  int64
 24  underlying_ticker                59276 non-null  object
 25  underlying_price                 0 non-null      float64
 26  underlying_change_to_break_even  0 non-null      float64
 27  underlying_last_updated          0 non-null      float64
 28  underlying_timeframe             0 non-null      float64
dtypes: float64(21), int64(2), object(6)
memory usage: 13.1+ MB

In [22]:
day_vol_gt_100 = (df2['day_volume'] > 10000)

In [23]:
df3=df2.loc[day_vol_gt_100,]

In [24]:
df4=df3.sort_values(by='day_volume', ascending=False)

In [25]:
df4.shape

(721, 29)

In [26]:
df5=df4[0:100]

In [27]:
df5

,date,ticker,contract_type,exercise_style,expiration_date,shares_per_contract,strike_price,day_change,day_change_percent,day_close,...,theta,vega,implied_volatility,break_even_price,open_interest,underlying_ticker,underlying_price,underlying_change_to_break_even,underlying_last_updated,underlying_timeframe
146,2025-08-18,O:SPY250829C00645000,call,american,2025-08-29,100,645.0,-4.52,-97.000,0.14,...,NaN,NaN,20.000000,NaN,16147,SPY,NaN,NaN,NaN,NaN
34018,2025-08-22,O:SPY250829C00645000,call,american,2025-08-29,100,645.0,-4.52,-97.000,0.14,...,NaN,NaN,20.000000,NaN,16147,SPY,NaN,NaN,NaN,NaN
17082,2025-08-20,O:SPY250829C00645000,call,american,2025-08-29,100,645.0,-4.52,-97.000,0.14,...,NaN,NaN,20.000000,NaN,16147,SPY,NaN,NaN,NaN,NaN
42486,2025-08-25,O:SPY250829C00645000,call,american,2025-08-29,100,645.0,-4.52,-97.000,0.14,...,NaN,NaN,20.000000,NaN,16147,SPY,NaN,NaN,NaN,NaN
50954,2025-08-26,O:SPY250829C00645000,call,american,2025-08-29,100,645.0,-4.52,-97.000,0.14,...,NaN,NaN,20.000000,NaN,16147,SPY,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17087,2025-08-20,O:SPY250829C00650000,call,american,2025-08-29,100,650.0,-0.92,-98.900,0.01,...,NaN,NaN,20.000000,NaN,35212,SPY,NaN,NaN,NaN,NaN
50959,2025-08-26,O:SPY250829C00650000,call,american,2025-08-29,100,650.0,-0.92,-98.900,0.01,...,NaN,NaN,20.000000,NaN,35212,SPY,NaN,NaN,NaN,NaN
151,2025-08-18,O:SPY250829C00650000,call,american,2025-08-29,100,650.0,-0.92,-98.900,0.01,...,NaN,NaN,20.000000,NaN,35212,SPY,NaN,NaN,NaN,NaN
22314,2025-08-20,O:SPY260116P00575000,put,american,2026-01-16,100,575.0,0.61,9.145,7.28,...,-0.064592,0.912543,0.214172,NaN,126229,SPY,NaN,NaN,NaN,NaN
56186,2025-08-26,O:SPY260116P00575000,put,american,2026-01-16,100,575.0,0.61,9.145,7.28,...,-0.064592,0.912540,0.214173,NaN,126229,SPY,NaN,NaN,NaN,NaN

In [31]:
df5.to_csv('top100.csv', index=False)

In [30]:
df4.shape

(721, 29)